{% set name = "enaml" %}
{% set version = "0.10.4" %}
{% set sha256 = "6733ff89cf3e3000ae7e8ea7fc8a9d1aef57cce1a5df1a3e986518aea29776ec" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - enaml-run = enaml.runner:main
  osx_is_app: True
  skip_compile_pyc:
    - "*/enaml/core/byteplay/*.py"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - atom >=0.4.2
    - kiwisolver >=1.0.0
    - ply >=3.4
    - qtpy >=1.3
  run:
    - python
    - python.app  # [osx]
    - atom >=0.4.2
    - pyqt
    - qtpy >=1.3
    - kiwisolver >=1.0.0
    - ply >=3.4

test:
  commands:
    - enaml-run --help
  imports:
    - enaml
    - enaml.callableref
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.signaling
    - enaml.weakmethod
    - enaml.core.api
    - enaml.widgets.api
    - enaml.layout.api

about:
  home: https://github.com/nucleic/enaml
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Declarative DSL for building rich user interfaces in Python
  doc_url: http://nucleic.github.io/enaml/docs/
  dev_url: https://github.com/nucleic/enaml

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - tacaswell
