{% set name = "enaml" %}
{% set version = "0.10.2" %}
{% set sha256 = "f10e7c711c34f76618f54aa88aafde5e931aba2bbe8ace844f42160676f63007" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - enaml-run = enaml.runner:main
  osx_is_app: true

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - future
    - python.app  # [osx]
    - atom >=0.4.1
    - pyqt
    - qtpy >=1.3
    - kiwisolver >=1.0.0
    - ply >=3.4
    - bytecode

test:
  commands:
    - enaml-run --help
  imports:
    - enaml
    - enaml.callableref
    - enaml.weakmethod
    - enaml.signaling
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.core.api
    - enaml.widgets.api
    - enaml.layout.api

about:
  home: https://github.com/nucleic/enaml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Declarative DSL for building rich user interfaces in Python
  doc_url: http://nucleic.github.io/enaml/docs/
  dev_url: https://github.com/nucleic/enaml

extra:
  recipe-maintainers:
    - blink1073
    - licode
    - MatthieuDartiailh
    - tacaswell
