travis:
  secure:
    BINSTAR_TOKEN: NXwp3kTvfJLbGvs9clmY0pYYlErbr3BZ238ckAMyMkC/57QW4ua+8SzfXxo2f9A0xCSQu8CabK5S/kBd3iJpRepBetjcq0Xi36qTrweMQ0YfuNYR1EdZsLJwAP2Fryq85hbgw+uNzoq6kB1ZA/K/c3oOnFYSydN/DrxYaq6lVjw960OfQ8avZVJlEOTwhgo7GwHahliV2UL/LwavIHaIV3lutTXcT1X0dWvc/93+AvG23+BOILWeiKWdPKIIUsX51yVQSDRTWf18SRIj97fncIue3/6s6dDROrd/Bbnr1AHoJAgW7es0pG/8+/q9u1NQUk1Fi35sj0wxJ/xbCGeGH56Ty99AtMKw3zc/N0RJT0QDeoF5vSkSblypgfsWc/LLTKD7ATrjW+yB36JTLPxNcDVukncvKRoxWK0TxomeZUNkv43tZHpPgT62QUT3k0HEgILdjCDC2DLXDetBgU42yaego+/7cIojeRDUQ/NRbop8roA5ypeleuq0otPCgyWXG3ry13NtYoWiUx50qFCnN51FUPl7W3fON7cTZqwqNsEetnR5SQZNiEgvNtvk/vBZd+S+GqFoLqsdvOEWGIwu3yEgY7bDW51odCvCQ3MfMG0pMm5kbkdaykJN2FWXZ8F7mNfjx7PnR3xusL2WJNsKpcQoNY2+SD2o27w+Md/RcbI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
