appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: w8UI3NvQvrbPca00aiSY/fEzwGoIOTI8f51X2OMjKTnDT2MwGLIwzSKukcXWFk2jf0yhRJTcVeJrevGkLBGQx6T/rezvL6+674QK6En0/o6Tnz75txh15vniTgJ/ljZQPwwgoS9C8KRpF6e6NKQZIDzNLXKBO7NzO1aqiyYJ977i8USwvJ+7x8WuPIfWzdAYlriAQSQ8KNOJom27rXleNbK9nTPtioa/qfVpiRHjkusWXYFt7P3yCSlPnGdjkwL8piImzb30pxumNqAqofB3RkikTcQStxF69vpNVzqKoIte1kJjNwdWxWD7CAcKjuqNhE7jYbaaBWnCTpRJm4tVdomK37TFdey8Wab+tvkjvkhbL3hObeTVqyZ/mnkxoKphfr7YRpII1CyNjRsHSeERnc/BpzrkemAPuCoHttELT0V02ThBfLWxacXuOMS8n2nKjsAETnK2lJEikgNTolPrbLmh+5ukK0OHTnVMYnjUmOJRBuWnYQvCTtYS5A8a6U2IuHdukgswEL8NOUDyWUlhBvSL5g1yLLuuvWgJI/DQqC87MX9eitDSnq8PiyaveUBcywv3ryXTLmrJRj1C2PY38JRUGTyPOarkhaYg5gJ/hMEgwvDoXLJ62c/iH/xyJv3dmEezm3P0cDS5UBCJ4auoemWxQsvrBg9lKRfC2IabMHk=}
